### ISSUE TITLE
无法正确读取卡牌套数

### ISSUE THREAD

**Issue by adminerest** [chr233/CardTradeExtension#1]
**Describe the bug / Bug 描述**
使用`!sendcardset`以及`!2sendcardset`命令时无法正确读取卡牌套数，卡牌总张数也不正确   

**Error Log / 错误日志**
Command: `!sendcardset 570 5 <tradelink>`   
Total Cards: `167 + 400 + 571 + 142 + 410 + 243 + 334 + 231 = 2498`   

![截屏2023-03-19 19 47 11](https://user-images.githubusercontent.com/43260539/226173298-ece4dd72-ce2d-4263-9627-1378f454754e.png)
![截屏2023-03-19 19 47 45](https://user-images.githubusercontent.com/43260539/226173309-13f8eb87-c968-43c7-9f10-9ae4603ed3ba.png)
<img width="723" alt="截屏2023-03-19 19 47 27" src="https://user-images.githubusercontent.com/43260539/226173312-18917c7e-90ed-4c41-8a4c-6c2e60ed6b3f.png">
```txt
CardTradeExtension 遇到错误, 日志如下
==========================================
 - 原始消息: TEST
 - Access: Owner
 - ASF 版本: 5.4.3.2
 - 插件版本: 1.0.0.0
==========================================
"CardTradeExtension": {
    "EULA": true,
    "Statistic": false,
    "DisabledCmds": [
      "foo",
      "bar"
    ],
    "MaxItemPerTrade": 255
  }
==========================================
```

**Comment by chr233** [comment]
todo，最近比较忙，等几天吧
