### ISSUE TITLE
SENDCARDSET did not work

### ISSUE THREAD

**Issue by Domjul** [chr233/CardTradeExtension#17]
**Describe the bug / Bug 描述**
Describe what the bug is

Hello! If i use the command SENDCARDSET [Bots] AppId SetCount TradeLink i get the error message, that there are no full cardsets, but i have tradeable cardsets.

This is the message that i get: 

交易前库存状态:
2861720: 总计 150张, 每套 -1张, 可交易 0套 +0张, 不可交易 0套 +0张

I have full winter sale card sets in my inventory, but i cant trade them with the command SENDCARDSET [Bots] AppId SetCount TradeLink

Second problem: 

If i use the command SENDCARDSETBOT [Bots] AppId SetCount TargetBot 
i get the error message 

参数无效, 示例 730 2 交易链接

It seems that the option TargetBot did not use the Botname.

Can you check the 2 problems please? 
Thank you very much!

**Comment by chr233** [comment]
need generic version

**Comment by Domjul** [comment]
Hello chr233! 
Thank you for your answer!
I use generic version but still have this problem. 
![Screenshot 2024-12-22 093421](https://github.com/user-attachments/assets/2e8bd2c4-848c-4ff1-99ad-0437a6a88e45)
Or did i use the wrong ASF version, did the Plugin only works until ASF -> 6.0.7.5 ? I use ASF ASF 6.1.0.3 maybe thats why i get the error?

**Comment by Domjul** [comment]
I have installed now ASF 6.0.7.5 - generic - but if i use SENDCARDSET [Bots] AppId SetCount TradeLink i get this error message:

Pre-trade inventory status:
2861720: 总计 500张, 每套 -1张, 可交易 0套 +0张, 不可交易 0套 +0张
Failed to send trade offer, not enough cards available for trade

**Comment by chr233** [comment]
> I have installed now ASF 6.0.7.5 - generic - but if i use SENDCARDSET [Bots] AppId SetCount TradeLink i get this error message:
> 
> Pre-trade inventory status:
> 2861720: 总计 500张, 每套 -1张, 可交易 0套 +0张, 不可交易 0套 +0张
> Failed to send trade offer, not enough cards available for trade
> 


you need use "fsl botname" to update card set cache

**Comment by Domjul** [comment]
It works now! Thank you so much for your help!
