### ISSUE TITLE
No one command work

### ISSUE THREAD

**Issue by OliverTrust** [chr233/CardTradeExtension#2]
![2](https://user-images.githubusercontent.com/33681835/229314656-f47339ee-6.png)

On last ASF version same problems (5.4.4.3)

**Comment by chr233** [comment]
current version only works in 5.4.3.2

**Comment by OliverTrust** [comment]
Screenshot with exceptions made in 5.4.3.2

**Comment by chr233** [comment]
working on fixing bugs, and will upgrade to 5.4.4.3 later

**Comment by chr233** [comment]
If there is someone needs english version of this plugin?
