### ISSUE TITLE
FULLSETLIST problem

### ISSUE THREAD

**Issue by OliverTrust** [chr233/CardTradeExtension#3]
![Снимок экрана 2023-07-16 203958](https://github.com/chr233/ASFTradeExtension/assets/33681835/f42a0789-6ac8-4113-b651-df0b16337ebc)

I have a problem on current version of extension

**Comment by OliverTrust** [comment]
On version 1.0.5.0 (pre-release) same problem

**Comment by chr233** [comment]
I got it

**Comment by chr233** [comment]
too busy, it may takes more time to fix

**Comment by OliverTrust** [comment]
I'm waiting and believe <3

**Comment by chr233** [comment]
> I'm waiting and believe <3

lol

**Comment by chr233** [comment]
some code are not tested yet, you'd better test yourself (card set trade function)

**Comment by OliverTrust** [comment]
AWESOME! Plugin working! Thank you very much 
![2](https://github.com/chr233/ASFTradeExtension/assets/33681835/b94a0dfb-5f05-4a21-92eb-e32c9029adb8)
